title: Faraz Mubeen Haider
description: Portfolio and Projects of Faraz Mubeen
theme: minima
baseurl: "/Faraz_Mubeen"  # Your repository name
url: "https://faraz6180.github.io"
markdown: kramdown
plugins:
  - jekyll-feed
