theme: "jekyll-theme-slate"  # Make sure the theme name is complete

title: "My Website"
description: "Welcome to my personal website!"
baseurl: ""
url: "https://yourusername.github.io"

nav:
  - Resume: "/resume"
  - Projects: "/projects"
  - Medium: "/medium"
  - LinkedIn: "/linkedin"
  - About: "/about"
