theme: jekyll-theme-cayman
title: My Website
description: "Welcome to my personal website!"
baseurl: ""
url: "https://faraz6180.github.io/Faraz_Mubeen"

nav:
  - Resume: "/resume"
  - Projects: "/projects"
  - Medium: "/medium"
  - LinkedIn: "/linkedin"
  - About: "/about"
