title: Faraz Mubeen Haider
description: Portfolio and Projects of Faraz Mubeen
theme: minima
baseurl: "/Faraz_Mubeen"  # Add your repository name here
url: "https://faraz6180.github.io"
markdown: kramdown
plugins:
  - jekyll-feed
